Job:
    run_mode: "Training"  
    #{Training, Predict, Repeat, CV, Hyperparameter, Ensemble, Analysis}
    Training:
        job_name: "MP_MegNet_training"
        reprocess: "False"    
        model: CGCNN_demo
        load_model: "False"
        save_model: "False"
        model_path: "./Results/Models/cgcnn_old.pth"
        write_output: "False"
        parallel: "False"
        #seed=0 means random initalization
        seed: 0        

    Predict:
        job_name: "MP_BG"
        reprocess: "False"    
        model_path: "./Results/CGCNN_Model/CGCNN_MP_robofail_bandgap.pth"
        write_output: "True"
        seed: 0     
    Repeat:
        job_name: "my_repeat_job"
        reprocess: "False"    
        model: CGCNN_demo
        model_path: "./Results/Models/cgcnn.pth"
        write_output: "False"
        parallel: "True"
        seed: 0      
        ###specific options
        #number of repeat trials
        repeat_trials: 5
    Hyperparameter:
        job_name: "my_hyperparameter_job"
        reprocess: "False"    
        model: CGCNN_demo
        seed: 0  
        ###specific options   
        hyper_trials: 10
        #number of concurrent trials (can be greater than number of GPUs)
        hyper_concurrency: 8
        #frequency of checkpointing and update (default: 1)
        hyper_iter: 1
        #resume a previous hyperparameter optimization run
        hyper_resume: "True"
        #Verbosity of ray tune output; available: (1, 2, 3)
        hyper_verbosity: 1
        #Delete processed datasets
        hyper_delete_processed: "True"
Processing:
    #Whether to use "inmemory" or "large" format for pytorch-geometric dataset. Reccomend inmemory unless the dataset is too large
    dataset_type: "inmemory"  
    #Path to data files
    data_path: "/data"
    #Path to target file within data_path
    target_path: "targets.csv"
    #Method of obtaining atom idctionary: available:(provided, default, blank, generated)
    dictionary_source: "generated"   
    #Path to atom dictionary file within data_path
    dictionary_path: "atom_dict.json"     
    #Format of data files (limit to those supported by ASE)
    data_format:  "cif"
    #Print out processing info 
    verbose: "True"
    #graph specific settings 
    graph_max_radius : 8.0
    graph_max_neighbors : 12
    voronoi: "False"
    edge_features: "True"
    graph_edge_length : 50
    #SM specific settings
    SM_descriptor: "False"
    #SOAP specific settings
    SOAP_descriptor: "False"
    SOAP_rcut : 8.0
    SOAP_nmax : 6
    SOAP_lmax : 4
    SOAP_sigma : 0.3

Training:     
    #Index of target column in targets.csv
    target_index: 0
    #Loss functions (from pytorch) examples: l1_loss, mse_loss, binary_cross_entropy
    loss: "l1_loss"
    #Ratios for train/val/test split out of a total of 1  
    train_ratio: 0.99
    val_ratio: 0.01
    test_ratio: 0.01
    #Training print out frequency (print per n number of epochs)
    verbosity: 1
    
Models:        
    CGCNN_demo:
        model: CGCNN
        dim1: 100
        dim2: 150
        pre_fc_count: 1
        gc_count: 4
        post_fc_count: 3
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 10
        lr: 0.002
        batch_size: 8
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":2, "min_lr":0.00001, "threshold":0.002}                        
    